In [1]:
# trade_data_generator.py
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import time

def generate_futures_price(symbol, trade_time, num_steps):
    """Generates realistic price series with proper scoping"""
    # Configuration INSIDE function
    base_price_dict = {
        'ESM5': 4250.0,
        'ZBM5': 142000,
        'NQM5': 16500.0,
        'RTY': 2000.0,
        'GC': 1950.0,
        'CL': 75.0
    }
    
    volatility_profiles = {
        'ESM5': {'annual_vol': 18, 'tick_size': 0.25},
        'ZBM5': {'annual_vol': 12, 'tick_size': 1},
        'NQM5': {'annual_vol': 10, 'tick_size': 0.5},
        'RTY': {'annual_vol': 15, 'tick_size': 0.1},
        'GC': {'annual_vol': 15, 'tick_size': 0.1},
        'CL': {'annual_vol': 35, 'tick_size': 0.01}
    }

    # Validate inputs
    if symbol not in base_price_dict:
        raise ValueError(f"Unconfigured symbol: {symbol}")
        
    # Set up parameters
    base_price = base_price_dict[symbol]
    annual_vol = volatility_profiles[symbol]['annual_vol'] / 100  # Convert to decimal
    tick_size = volatility_profiles[symbol]['tick_size']
    
    # Time scaling
    dt = 1/(252*6.5*60)  # 1 minute intervals in a trading year
    volatility = annual_vol * np.sqrt(dt * num_steps)
    
    # Generate price path with valid seed
    seed_value = int(trade_time.timestamp() * 1000) % (2**32 - 1)
    np.random.seed(seed_value)
    returns = np.random.normal(0, volatility, num_steps)
    prices = base_price * np.exp(np.cumsum(returns))
    
    return np.round(prices / tick_size) * tick_size

# Main script
NUM_TRADES = 250  # 250 rows of trade data
SYMBOLS = ['ESM5', 'ZBM5', 'NQM5', 'RTY', 'GC', 'CL']
ACCOUNTS = [f'TRADER_{chr(i)}' for i in range(65, 70)]  # A-E
start_time = datetime(2024, 11, 1, 8, 30, 0)


# Generate records
records = []
for i in range(NUM_TRADES):
    trade_time = start_time + timedelta(milliseconds=i*50 + np.random.randint(0,50))
    symbol = np.random.choice(SYMBOLS, p=[0.3,0.2,0.15,0.15,0.1,0.1])
    price = generate_futures_price(symbol, trade_time, 1)[0]
    
    records.append({
        'TradeID': f"T{i+1:04d}", 
        'B/S': np.random.choice(['B', 'S'], p=[0.55 + (i%10)*0.01, 0.45 - (i%10)*0.01]),
        'OrdQty': np.random.randint(1, 500),
        'Exch': 'CME' if symbol != 'RTY' else 'ICE',
        'Contract': symbol,
        'Price': price,
        'Account': f'TRADER_{chr(65 + i%5)}',
        'TIF': np.random.choice(['Day', 'GTC', 'IOC'], p=[0.5, 0.3, 0.2]),
        'Type': np.random.choice(['Limit', 'Market', 'Stop'], p=[0.6, 0.3, 0.1]),
        'Timestamp': trade_time.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
    })

# Create base DataFrame
df = pd.DataFrame(records)

# Sample for executed and reported trades
executed_df = df.sample(frac=0.98, random_state=42).reset_index(drop=True)
executed_df['Price'] = executed_df['Price'].round(2)
reported_df = executed_df.copy()

# Introduce discrepancies in reported_df
reported_df = reported_df.sample(frac=0.98).reset_index(drop=True)
reported_df['Price'] = reported_df['Price'] * np.random.uniform(0.9995, 1.0005, size=len(reported_df))
reported_df['OrdQty'] = reported_df['OrdQty'].apply(lambda x: round(x/5)*5)
reported_df['Timestamp'] = pd.to_datetime(reported_df['Timestamp']) + pd.to_timedelta(np.random.randint(1,3,size=len(reported_df)), unit='s')
reported_df['Price'] = reported_df['Price'].round(2)

# Save to CSV
executed_df.to_csv('executed_trades.csv', index=False)
reported_df.to_csv('reported_trades.csv', index=False)

# Print summary
print("Generated 2 CSV files with Trade IDs:")
print(f"- executed_trades.csv: {len(executed_df)} trades")
print(f"- reported_trades.csv: {len(reported_df)} trades")
print("\nSample data:")
print(executed_df[['TradeID', 'Contract', 'B/S', 'OrdQty', 'Price', 'Account', 'Timestamp']].head(3).to_string(index=False))

Generated 2 CSV files with Trade IDs:
- executed_trades.csv: 245 trades
- reported_trades.csv: 240 trades

Sample data:
TradeID Contract B/S  OrdQty    Price  Account               Timestamp
  T0143      RTY   B      66   1999.6 TRADER_C 2024-11-01 08:30:07.123
  T0007     ZBM5   S     458 141945.0 TRADER_B 2024-11-01 08:30:00.303
  T0098     ZBM5   B     245 142105.0 TRADER_C 2024-11-01 08:30:04.850

In [2]:
import pandas as pd

exec_df = pd.read_csv('executed_trades.csv')
rep_df = pd.read_csv('reported_trades.csv')

In [3]:
# Merge based on unique TradeID
merged = pd.merge(executed_df, reported_df, on='TradeID', how='outer', suffixes=('_exec', '_rep'), indicator=True)

# Identify trade-level mismatches (TradeID exists in only one DataFrame)
missing_trades = merged[merged['_merge'] != 'both']

# Identify field-level mismatches (same TradeID, but fields differ)
field_mismatches = merged[
    (merged['_merge'] == 'both') & (
        (merged['Price_exec'] != merged['Price_rep']) |
        (merged['OrdQty_exec'] != merged['OrdQty_rep']) |
        (merged['Timestamp_exec'] != merged['Timestamp_rep']) |
        (merged['B/S_exec'] != merged['B/S_rep']) |
        (merged['TIF_exec'] != merged['TIF_rep']) |
        (merged['Type_exec'] != merged['Type_rep']) |
        (merged['Exch_exec'] != merged['Exch_rep']) |
        (merged['Contract_exec'] != merged['Contract_rep']) |
        (merged['Account_exec'] != merged['Account_rep'])
    )
]

# Show some mismatches
print("Missing Trades:")
print(missing_trades.head())

print("\nField Mismatches:")
print(field_mismatches.head())

Missing Trades:
    TradeID B/S_exec  OrdQty_exec Exch_exec Contract_exec  Price_exec  \
15    T0017        B          383       CME          ESM5     4250.75
47    T0049        B          431       CME          NQM5    16505.00
115   T0120        B          453       ICE           RTY     2000.00
141   T0146        B          353       CME          ZBM5   141955.00
142   T0147        S           37       CME          NQM5    16487.00

    Account_exec TIF_exec Type_exec           Timestamp_exec B/S_rep  \
15      TRADER_B      IOC     Limit  2024-11-01 08:30:00.833     NaN
47      TRADER_D      GTC     Limit  2024-11-01 08:30:02.448     NaN
115     TRADER_E      GTC     Limit  2024-11-01 08:30:05.971     NaN
141     TRADER_A      Day     Limit  2024-11-01 08:30:07.289     NaN
142     TRADER_B      IOC     Limit  2024-11-01 08:30:07.331     NaN

     OrdQty_rep Exch_rep Contract_rep  Price_rep Account_rep TIF_rep Type_rep  \
15          NaN      NaN          NaN        NaN         NaN     NaN      NaN
47          NaN      NaN          NaN        NaN         NaN     NaN      NaN
115         NaN      NaN          NaN        NaN         NaN     NaN      NaN
141         NaN      NaN          NaN        NaN         NaN     NaN      NaN
142         NaN      NaN          NaN        NaN         NaN     NaN      NaN

    Timestamp_rep     _merge
15            NaT  left_only
47            NaT  left_only
115           NaT  left_only
141           NaT  left_only
142           NaT  left_only

Field Mismatches:
  TradeID B/S_exec  OrdQty_exec Exch_exec Contract_exec  Price_exec  \
0   T0001        B          225       CME          ESM5     4251.25
1   T0002        S          282       CME          NQM5    16496.00
2   T0003        S          123       CME          ZBM5   142015.00
3   T0004        S           91       CME          ZBM5   142077.00
4   T0005        S          260       CME          ZBM5   141984.00

  Account_exec TIF_exec Type_exec           Timestamp_exec B/S_rep  \
0     TRADER_A      GTC    Market  2024-11-01 08:30:00.030       B
1     TRADER_B      Day     Limit  2024-11-01 08:30:00.070       S
2     TRADER_C      GTC    Market  2024-11-01 08:30:00.138       S
3     TRADER_D      Day      Stop  2024-11-01 08:30:00.154       S
4     TRADER_E      Day    Market  2024-11-01 08:30:00.216       S

   OrdQty_rep Exch_rep Contract_rep  Price_rep Account_rep TIF_rep Type_rep  \
0       225.0      CME         ESM5    4252.90    TRADER_A     GTC   Market
1       280.0      CME         NQM5   16504.09    TRADER_B     Day    Limit
2       125.0      CME         ZBM5  142072.35    TRADER_C     GTC   Market
3        90.0      CME         ZBM5  142130.08    TRADER_D     Day     Stop
4       260.0      CME         ZBM5  141962.31    TRADER_E     Day   Market

            Timestamp_rep _merge
0 2024-11-01 08:30:02.030   both
1 2024-11-01 08:30:01.070   both
2 2024-11-01 08:30:01.138   both
3 2024-11-01 08:30:01.154   both
4 2024-11-01 08:30:02.216   both

In [5]:
missing_trades.to_csv('missing_trades_report.csv', index=False)
field_mismatches.to_csv('field_level_discrepancies.csv', index=False)

In [7]:
missing_df = pd.read_csv('missing_trades_report.csv')
field_mismatch_df = pd.read_csv('field_level_discrepancies.csv')

In [9]:
from sqlalchemy import create_engine

# Replace this with your actual password if different
engine = create_engine("mysql+mysqlconnector://root:4452859@localhost/trade_db")

missing_df.to_sql(name='missing_trades_report', con=engine, if_exists='replace', index=False)
field_mismatch_df.to_sql(name='field_level_discrepancies', con=engine, if_exists='replace', index=False)

-1

In [12]:
query = """
SELECT Contract_exec AS contract, COUNT(*) AS mismatch_count
FROM field_level_discrepancies
GROUP BY Contract_exec
ORDER BY mismatch_count DESC;
"""
contract_issues = pd.read_sql(query, engine)
display(contract_issues)

  contract  mismatch_count
0     ESM5              72
1     ZBM5              56
2      RTY              36
3     NQM5              33
4       GC              26
5       CL              17

In [13]:
query = """
SELECT Account_exec AS account, COUNT(*) AS missing_count
FROM missing_trades_report
GROUP BY Account_exec;
"""
account_missing_summary = pd.read_sql(query, engine)
display(account_missing_summary)

    account  missing_count
0  TRADER_B              2
1  TRADER_D              1
2  TRADER_E              1
3  TRADER_A              1

In [14]:
merged = pd.merge(executed_df, reported_df, on='TradeID', how='inner', suffixes=('_exec', '_rep'))
merged['Timestamp_exec'] = pd.to_datetime(merged['Timestamp_exec'])
merged['Timestamp_rep'] = pd.to_datetime(merged['Timestamp_rep'])

In [15]:
from datetime import timedelta

# Price difference <= 0.01% of executed price
price_diff = (merged['Price_exec'] - merged['Price_rep']).abs()
price_within_range = price_diff <= (0.0001 * merged['Price_exec'])

# OrdQty difference <= 1 unit
qty_diff = (merged['OrdQty_exec'] - merged['OrdQty_rep']).abs()
qty_within_range = qty_diff <= 1

# Timestamp difference <= 1 second
time_diff = (merged['Timestamp_exec'] - merged['Timestamp_rep']).abs()
time_within_range = time_diff <= timedelta(seconds=1)

In [16]:
fuzzy_mismatches = merged[~(price_within_range & qty_within_range & time_within_range)]
display(fuzzy_mismatches[['TradeID', 'Contract_exec', 'Price_exec', 'Price_rep',
                          'OrdQty_exec', 'OrdQty_rep',
                          'Timestamp_exec', 'Timestamp_rep']].head())

,TradeID,Contract_exec,Price_exec,Price_rep,OrdQty_exec,OrdQty_rep,Timestamp_exec,Timestamp_rep
0,T0143,RTY,1999.60,1998.92,66,65,2024-11-01 08:30:07.123,2024-11-01 08:30:08.123
1,T0007,ZBM5,141945.00,141927.30,458,460,2024-11-01 08:30:00.303,2024-11-01 08:30:02.303
2,T0098,ZBM5,142105.00,142138.99,245,245,2024-11-01 08:30:04.850,2024-11-01 08:30:05.850
4,T0113,ZBM5,141949.00,141911.28,144,145,2024-11-01 08:30:05.647,2024-11-01 08:30:07.647
5,T0182,ESM5,4253.75,4252.51,364,365,2024-11-01 08:30:09.076,2024-11-01 08:30:11.076

In [18]:
def label_fuzzy_mismatch(row):
    labels = []
    if abs(row['Price_exec'] - row['Price_rep']) > 0.0001 * row['Price_exec']:
        labels.append("Price")
    if abs(row['OrdQty_exec'] - row['OrdQty_rep']) > 1:
        labels.append("OrdQty")
    if abs(row['Timestamp_exec'] - row['Timestamp_rep']) > timedelta(seconds=1):
        labels.append("Timestamp")
    return ", ".join(labels)
fuzzy_mismatches = merged[~(price_within_range & qty_within_range & time_within_range)].copy()
fuzzy_mismatches['Mismatch_Fields'] = fuzzy_mismatches.apply(label_fuzzy_mismatch, axis=1)

In [19]:
print(fuzzy_mismatches.head(10))  # prints all columns

   TradeID B/S_exec  OrdQty_exec Exch_exec Contract_exec  Price_exec  \
0    T0143        B           66       ICE           RTY     1999.60
1    T0007        S          458       CME          ZBM5   141945.00
2    T0098        B          245       CME          ZBM5   142105.00
4    T0113        S          144       CME          ZBM5   141949.00
5    T0182        B          364       CME          ESM5     4253.75
6    T0198        S           17       CME          ESM5     4248.25
7    T0185        S            7       CME          ESM5     4250.00
8    T0010        S          122       CME          ESM5     4249.00
9    T0105        S          181       ICE           RTY     1999.30
10   T0201        B          259       ICE           RTY     2002.30

   Account_exec TIF_exec Type_exec          Timestamp_exec B/S_rep  \
0      TRADER_C      GTC     Limit 2024-11-01 08:30:07.123       B
1      TRADER_B      Day    Market 2024-11-01 08:30:00.303       S
2      TRADER_C      Day      Stop 2024-11-01 08:30:04.850       B
4      TRADER_C      GTC    Market 2024-11-01 08:30:05.647       S
5      TRADER_B      Day      Stop 2024-11-01 08:30:09.076       B
6      TRADER_C      Day     Limit 2024-11-01 08:30:09.877       S
7      TRADER_E      Day    Market 2024-11-01 08:30:09.233       S
8      TRADER_E      Day     Limit 2024-11-01 08:30:00.460       S
9      TRADER_E      Day     Limit 2024-11-01 08:30:05.215       S
10     TRADER_A      GTC     Limit 2024-11-01 08:30:10.002       B

    OrdQty_rep Exch_rep Contract_rep  Price_rep Account_rep TIF_rep Type_rep  \
0           65      ICE          RTY    1998.92    TRADER_C     GTC    Limit
1          460      CME         ZBM5  141927.30    TRADER_B     Day   Market
2          245      CME         ZBM5  142138.99    TRADER_C     Day     Stop
4          145      CME         ZBM5  141911.28    TRADER_C     GTC   Market
5          365      CME         ESM5    4252.51    TRADER_B     Day     Stop
6           15      CME         ESM5    4249.72    TRADER_C     Day    Limit
7            5      CME         ESM5    4250.51    TRADER_E     Day   Market
8          120      CME         ESM5    4248.11    TRADER_E     Day    Limit
9          180      ICE          RTY    1999.60    TRADER_E     Day    Limit
10         260      ICE          RTY    2002.87    TRADER_A     GTC    Limit

             Timestamp_rep           Mismatch_Fields
0  2024-11-01 08:30:08.123                     Price
1  2024-11-01 08:30:02.303  Price, OrdQty, Timestamp
2  2024-11-01 08:30:05.850                     Price
4  2024-11-01 08:30:07.647          Price, Timestamp
5  2024-11-01 08:30:11.076          Price, Timestamp
6  2024-11-01 08:30:11.877  Price, OrdQty, Timestamp
7  2024-11-01 08:30:11.233  Price, OrdQty, Timestamp
8  2024-11-01 08:30:01.460             Price, OrdQty
9  2024-11-01 08:30:07.215          Price, Timestamp
10 2024-11-01 08:30:12.002          Price, Timestamp

In [23]:
#Ensuring ative Python types
for col in fuzzy_mismatches.columns:
    fuzzy_mismatches[col] = fuzzy_mismatches[col].apply(lambda x: str(x) if isinstance(x, (np.str_, np.unicode_)) else x)

#Converting NaN to None (for SQL compatibility)
fuzzy_mismatches = fuzzy_mismatches.where(pd.notnull(fuzzy_mismatches), None)
#Uploading to SQL
fuzzy_mismatches.to_sql('fuzzy_field_mismatches', con=engine, if_exists='replace', index=False)

-1